import { BeforeInsert, Column, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';
import { TIMESTAMP } from '../config';

export const MESSAGE_TYPES = ['text', 'image', 'video', 'audio'] as const;
export type MessageType = (typeof MESSAGE_TYPES)[number];

@Entity('messages')
@Index(['recipientId', 'deliveredAt'])
@Index(['senderId', 'recipientId', 'createdAt'])
@Index(['senderId', 'clientId'], { unique: true })
export class Message {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // Id generated by the sending phone, so it can match the server's ack to its pending bubble.
  @Column()
  clientId: string;

  @Column()
  senderId: string;

  @Column()
  recipientId: string;

  @Column({ type: 'varchar', default: 'text' })
  type: MessageType;

  // Plain text for now. Once Signal Protocol is added this holds ciphertext only.
  @Column({ type: 'text' })
  body: string;

  // Set in code (not a DB default) so SQLite keeps millisecond precision and message order is stable.
  @Column({ type: TIMESTAMP })
  createdAt: Date;

  @BeforeInsert()
  stampCreatedAt() {
    this.createdAt ??= new Date();
  }

  @Column({ type: TIMESTAMP, nullable: true })
  deliveredAt: Date | null;

  @Column({ type: TIMESTAMP, nullable: true })
  readAt: Date | null;
}
